name: Build libmpv-android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux

      - name: Bundle (full)
        working-directory: ./buildscripts
        run: |
          chmod +x bundle_full.sh
          ./bundle_full.sh

      # ⭐ 创建 tag（只在 main）
      - name: Create tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag -f vnext
          git push origin vnext --force

      # ⭐ 上传 CI 构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libmpv-jars
          path: "*.jar"

      # ⭐ 发布到 GitHub Release
      - name: Publish Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: vnext
          draft: false
          prerelease: false
          files: |
            *.jar
